protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
    /**
     * Declares class-based actions.
     */
    public function actions()
    {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha'=>array(
                'class'=>'CCaptchaAction',
                'backColor'=>0x600000,
                'foreColor'=>0xF9DD1C,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page'=>array(
                'class'=>'CViewAction',
            ),
        );
    }
    
    public function actionIndex()
    {
        if (Yii::app()->user->isGuest) {
            $this->render('index');
        } else {
            //$user = Characters::model()->findByPk((int) Yii::app()->user->getId());
            $user = Yii::app()->user->character;
            $itemsInventory = Inventory::model()->findAllByAttributes(array('idCharacter' => (int) $user->id));
            
            $this->render('general', array('user' => $user, 'itemsInventory' => $itemsInventory));
        }
    }

    public function actionSelectRace()
    {
        $this->render('selectRace');
    }

    public function actionRegister($raceId)
    {
        $raceId = (int) $raceId;

        if (!$raceId || $raceId > 4 || $raceId < 1) {
            $this->redirect(array('site/selectRace'));
        }

        $registerForm = new RegisterForm();

        if (isset($_POST['ajax']) && $_POST['ajax'] === 'register-form') {
            echo CActiveForm::validate($registerForm);
        } else {
            if (isset($_POST['RegisterForm'])) {
                $registerForm->attributes = $_POST['RegisterForm'];
                $registerForm->idRace = $raceId;
                $registerForm->level = 1;
                $registerForm->gold = 10;
                $registerForm->idZone = 1;
                
                if ($registerForm->save()) {
                    Yii::app()->user->setFlash('register', Yii::t('app', 'You have registered successfully'));
                }
            }
        }

        $this->render('register', array(
            'registerForm' => $registerForm,
        ));
    }

    // AJAX
    // Devolvemos la cantidad de items que posee
    public function actionGetItemAmount()
    {
        if (!isset($_POST['TradeForm']) && !isset($_POST['TradeForm']['idItem'])) {
            $this->redirect(array('site/index'));
        }

        $data = Inventory::model()->findByAttributes(array(
            'idCharacter'   => Yii::app()->user->character->id,
            'idItem'        => (int) $_POST['TradeForm']['idItem'],
        ));

        if (!is_object($data)) {
            echo CHtml::tag('option', array('value' => 0), 0, true);
            return;
        }

        /*if ($data->custom) {
            $data->custom = unserialize($data->custom);
            $amount = $data->custom['amount'];
        } else {
            $amount = 1;
        }*/

        for ($i = 1; $i <= $data->amount; ++$i) {
            echo CHtml::tag('option', array('value' => $i), $i, true);
        }
    }

    public function actionSendPrivateMessage()
    {
        $messageModel = new Messages();
        $characters = Characters::model()->findAll();

        if (isset($_POST['ajax']) && $_POST['ajax'] === 'private-message-form') {
            echo CActiveForm::validate($messageModel);
        } else {
            if (isset($_POST['Messages'])) {
                $messageModel->attributes = $_POST['Messages'];
                $messageModel->idFrom = Yii::app()->user->character->id;
                
                if ($messageModel->save()) {
                    Yii::app()->user->setFlash('privateMessage', Yii::t('app', 'Your private message was sent'));
                } else {
                    Yii::app()->user->setFlash('privateMessageError', Yii::t('app', 'Your private message was not sent, please try again'));
                }
            }
        }

        $this->render('sendPrivateMessage', array(
            'messageModel'  => $messageModel,
            'characters'    => $characters,
        ));
    }

    public function actionDeleteMessage($id)
    {
        $message = Messages::model()->findByPk((int) $id);

        if (is_object($message)) {
            $message->delete();
        }

        $this->redirect(array('site/messages'));
    }

    public function actionMessages($id = null)
    {
        if ($id === null) {
            $messages = Messages::model()->findAllByAttributes(array(
                'idTo'  => Yii::app()->user->character->id,
            ));

            $this->render('messages', array('messages' => $messages));
        } else {
            $message = Messages::model()->findByPk((int) $id);

            if (!is_object($message) || (int) $message->idTo !== (int) Yii::app()->user->character->id) {
                Yii::app()->user->setFlash('messageError', Yii::t('app', 'Error on displaying the message'));
            }

            $this->render('viewMessage', array('message' => $message));
        }
    }
    public function actionDeclineTrade ($id)
    {
        $id = (int) $id;
        $trade = Trades::model()->findByPk($id);

        if (is_object($trade)) {
            $seller = Characters::model()->findByPk((int) $trade->idSeller);

            if (is_object($seller)) {
                $inventario = Inventory::model()->findByAttributes(array(
                    'idCharacter' => $seller->id,
                    'idItem' => $trade->idItem
                ));

                if(is_object($inventario)) {
                    $inventario->amount = $inventario->amount + $trade->amount;
                    $inventario->save();
                } else {
                    $inventario = new Inventory();

                    $inventario->idCharacter = $seller->id;
                    $inventario->idItem = $trade->idItem;
                    $inventario->custom = $trade->custom;

                    $inventario->save();
                    //que hay que enviar el mp a los dos (tanto comprador como vendedor) para notificación
                }
            }
        }
    }
    public function actionAcceptTrade($id)
    {
        $id = (int) $id;
        $trade = Trades::model()->findByPk((int) $id);

        if (is_object($trade)) {
            $buyer = Characters::model()->findByPk((int) Yii::app()->user->character->id);

            if ((int) $trade->idBuyer === (int) $buyer->id) {
                if ($trade->price <= $buyer->gold) {
                    $seller = Characters::model()->findByPk((int) $trade->idSeller);
                    
                    if (is_object($seller)) {
                        $inventoryBuyer = new Inventory();

                        $inventoryBuyer->idCharacter = $buyer->id;
                        $inventoryBuyer->idItem = $trade->idItem;
                        $inventoryBuyer->amount = $trade->amount;
                        $inventoryBuyer->custom = $trade->custom;

                        $inventoryBuyer->save();
                        
                        $buyer->gold = $buyer->gold - $trade->price;
                        $buyer->save();

                        $seller->gold = $seller->gold + $trade->price;
                        $seller->save();

                        $trade->delete();

                        Yii::app()->user->setFlash('trade', Yii::t('app', 'The trade was successfully done'));
                    } else {
                        Yii::app()->user->setFlash('tradeError', Yii::t('app', 'You can not accept the trade because the seller does not exist'));
                    }
                } else {
                    Yii::app()->user->setFlash('tradeError', Yii::t('app', 'You can not accept the trade because you do not have enough money'));
                }
            } else {
                Yii::app()->user->setFlash('tradeError', Yii::t('app', 'That trade does not includes you')); 
            }
        } else {
            Yii::app()->user->setFlash('tradeError', Yii::t('app', 'That trade does not exist'));
        }

        $this->render('acceptTrade');
    }

    public function actionTrade()
    {
        $tradeForm = new TradeForm();
        $characters = Characters::model()->findAll('id <> :id', array(':id' => Yii::app()->user->character->id));
        $inventoryItems = Inventory::model()->findAllByAttributes(array('idCharacter' => (int) Yii::app()->user->character->id));
        $inventoryItem;
        
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'trade-form') {
            echo CActiveForm::validate($tradeForm);
        } else {
            if (isset($_POST['TradeForm'])) {
                $tradeForm->attributes = $_POST['TradeForm'];
                $tradeForm->idSeller = Yii::app()->user->character->id;

                $inventoryItem = Inventory::model()->findByAttributes(array('idItem' => $tradeForm->idItem, 'idCharacter' => Yii::app()->user->character->id));

                if($tradeForm->amount < $inventoryItem->amount){
                    Yii::app()->user->setFlash('tradeError', Yii::t('app', 'You do not have this item stock'));
                } else {
                    if($tradeForm->amount === $inventoryItem->amount){
                        $inventoryItem->delete();
                    } else {
                        $inventoryItem->amount = $inventoryItem->amount - $tradeForm->amount;
                        $inventoryItem->save();
                    }

                    $tradeForm->save();
                    
                    $item = Items::model()->findByPk($tradeForm->idItem); // check here

                    $message = new Messages();

                    $message->idFrom = Yii::app()->user->character->id;
                    $message->idTo = $tradeForm->idBuyer;

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<!DOCTYPE HTML>
<html lang="es">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/normalize.css" />

    <!-- blueprint CSS framework -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
    <!--[if lt IE 8]>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
    <![endif]-->

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

    <title><?php echo CHtml::encode($this->pageTitle); ?></title>

    <?php Yii::app()->clientScript->registerCoreScript('jquery'); ?>
</head>

<body>

<div class="container" id="page">

    <div id="header">
        <div id="logo"><img src="<?php echo Yii::app()->request->baseUrl; ?>/images/logo.jpg" /></div>
    </div><!-- header -->

    <div class="separator-bar-alternative"></div>
    <div id="mainmenu">
        <?php 
        $items = array();
        $items[] = array('label'=>'Inicio', 'url'=>array('/site/index'));
        $items[] = array('label'=>'Registrate para jugar', 'url'=>array('/site/selectRace'), 'visible'=>Yii::app()->user->isGuest);
        $items[] = array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest);
        $items[] = array('label'=>'Clan', 'url' => array('site/showClans'), 'visible' => !Yii::app()->user->isGuest);

        if (!Yii::app()->user->isGuest) {
            $messages = Messages::model()->findAllByAttributes(array(
                'idTo'  => Yii::app()->user->character->id,
                'read'  => false,
            ));

            $messagesLabel = 'Messages';
            
            if (count($messages) > 0) {
                $messagesLabel .= ' (' . count($messages) . ')';
            }

            $items[] = array('label'=>$messagesLabel, 'url'=>array('site/messages'));
            $items[] = array('label'=>'Trade', 'url'=>array('site/trade'));
            $items[] = array('label'=>'Logout ('.Yii::app()->user->character->username.')', 'url'=>array('/site/logout'));
        }

        $this->widget('zii.widgets.CMenu',array(
            'items'=> $items
        )); 

        unset($items);
        ?>

        <div class="wood-separator-bar" style="height: 10px;"></div>

        <?php
        if (count($this->npcs) > 0) {
            foreach ($this->npcs as $npc) {
        ?>
                <div style="display: inline-block;">
                    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/humano_ico.jpg" />
                    <br />
                    <?php echo CHtml::link($npc->name, array('site/npc', 'name' => $npc->name)); ?>
                </div>
        <?php
            }
        }
        ?>
        <div class="clear"></div>
    </div><!-- mainmenu -->
    <div class="separator-bar-alternative"></div>

    <?php if(isset($this->breadcrumbs)):?>
        <?php $this->widget('zii.widgets.CBreadcrumbs', array(
            'links'=>$this->breadcrumbs,
        )); ?><!-- breadcrumbs -->
    <?php endif?>

    <?php echo $content; ?>

    <div class="clear"></div>

    <div id="footer">
        Idea original de <b>V. Buendia</b> ('<a href="http://sourceforge.net/projects/tierras/">Tierras de Leyenda</a>')<br />
        <p>Iron Fist</p>
        <?php echo Yii::powered(); ?>
    </div><!-- footer -->

</div><!-- page -->

</body>
</html>